//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polic.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDisease
    {
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Complaints { get; set; }
        public string JointInspection { get; set; }
        public string MainDiagnosis { get; set; }
        public string Therapy { get; set; }
        public Nullable<int> IdMedCard { get; set; }
        public int IdDisease { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
    }
}
