//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polic.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStaff
    {
        public string NameRole { get; set; }
        public string NameSpeciality { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MidleName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
        public Nullable<int> CabNumber { get; set; }
        public int Role { get; set; }
        public Nullable<int> IdSpeciality { get; set; }
    }
}
